"""Small dictionary-based localization layer."""

from __future__ import annotations

from ofertaks.app.config import DEFAULT_LANGUAGE

TRANSLATIONS: dict[str, dict[str, str]] = {
    "sq": {
        "app_title": "OfertaKS",
        "tagline": "Ofertat me te mira ne Kosove",
        "search": "Kerko produkt",
        "refresh": "Rifresko",
        "last_sync": "Sinkronizimi i fundit",
        "best_deals": "Ofertat me te mira",
        "offers": "Ofertat",
        "basket": "Lista",
        "stores": "Dyqanet",
        "settings": "Cilesimet",
        "home": "Kryefaqja",
        "favorites": "Te preferuarat",
        "diagnostics": "Diagnostika",
        "offline_data": "Te dhena offline",
        "no_offers": "Nuk ka oferta te ruajtura.",
        "syncing": "Duke rifreskuar ofertat...",
        "best_price": "Cmimi me i mire",
        "price_history": "Historia e cmimit",
        "not_enough_history": "Nuk ka histori te mjaftueshme",
        "copy_diagnostics": "Kopjo raportin",
        "add": "Shto",
        "clear": "Pastro",
        "one_store": "Nje dyqan",
        "two_stores": "Maksimum 2 dyqane",
        "any_store": "Me lire gjithsej",
        "excellent_deal": "Oferta shume e mire",
        "good_deal": "Oferta e mire",
        "average_deal": "Oferta mesatare",
        "weak_deal": "Oferta e dobet",
    },
    "fr": {
        "app_title": "OfertaKS",
        "tagline": "Les meilleures offres au Kosovo",
        "search": "Chercher un produit",
        "refresh": "Actualiser",
        "last_sync": "Derniere synchro",
        "best_deals": "Meilleures offres",
        "offers": "Offres",
        "basket": "Panier",
        "stores": "Magasins",
        "settings": "Parametres",
        "home": "Accueil",
        "favorites": "Favoris",
        "diagnostics": "Diagnostic",
        "offline_data": "Donnees hors ligne",
        "no_offers": "Aucune offre en cache.",
        "syncing": "Actualisation des offres...",
        "best_price": "Meilleur prix",
        "price_history": "Historique du prix",
        "not_enough_history": "Pas assez d'historique",
        "copy_diagnostics": "Copier le rapport",
        "add": "Ajouter",
        "clear": "Effacer",
        "one_store": "Un seul magasin",
        "two_stores": "Maximum 2 magasins",
        "any_store": "Moins cher globalement",
        "excellent_deal": "Excellente offre",
        "good_deal": "Bonne offre",
        "average_deal": "Offre moyenne",
        "weak_deal": "Offre faible",
    },
    "en": {
        "app_title": "OfertaKS",
        "tagline": "Best supermarket deals in Kosovo",
        "search": "Search product",
        "refresh": "Refresh",
        "last_sync": "Last sync",
        "best_deals": "Best deals today",
        "offers": "Offers",
        "basket": "Basket",
        "stores": "Stores",
        "settings": "Settings",
        "home": "Home",
        "favorites": "Favorites",
        "diagnostics": "Diagnostics",
        "offline_data": "Offline data",
        "no_offers": "No cached offers.",
        "syncing": "Refreshing offers...",
        "best_price": "Best price",
        "price_history": "Price history",
        "not_enough_history": "Not enough history",
        "copy_diagnostics": "Copy report",
        "add": "Add",
        "clear": "Clear",
        "one_store": "One store",
        "two_stores": "Maximum 2 stores",
        "any_store": "Cheapest overall",
        "excellent_deal": "Excellent deal",
        "good_deal": "Good deal",
        "average_deal": "Average deal",
        "weak_deal": "Weak deal",
    },
}


def t(key: str, language: str | None = None) -> str:
    lang = language or DEFAULT_LANGUAGE
    return TRANSLATIONS.get(lang, TRANSLATIONS["en"]).get(
        key, TRANSLATIONS["en"].get(key, key)
    )
