"""English UI strings."""

STRINGS = {
    "add": "Add",
    "all": "All",
    "any_store": "Cheapest overall",
    "app_title": "OfertaKS",
    "average_deal": "Average deal",
    "basket": "Shopping list",
    "best_deals": "Best offers",
    "best_price": "Best price",
    "clear": "Clear",
    "copy_diagnostics": "Copy diagnostic report",
    "details": "Details",
    "diagnostics": "Diagnostics",
    "excellent_deal": "Excellent deal",
    "favorites": "Favorites",
    "good_deal": "Good deal",
    "home": "Home",
    "language": "Language",
    "language_saved": "Language saved",
    "largest_discount": "Largest discount",
    "last_sync": "Last updated",
    "missing_items": "missing",
    "nearby": "Nearby",
    "newest": "Newest",
    "no_offers": "No offers found.",
    "not_enough_history": "Not enough history",
    "not_matched": "not matched",
    "offers": "Offers",
    "offline_data": "Offline data",
    "one_store": "One store",
    "price_history": "Price history",
    "price_per_unit": "Price per unit",
    "recipes": "Recipes",
    "refresh": "Refresh",
    "retry": "Retry",
    "search": "Search product",
    "settings": "Settings",
    "sort_best_deals": "Best offers",
    "sort_lowest_price": "Lowest price",
    "stores": "Stores",
    "syncing": "Refreshing offers...",
    "tagline": "Best supermarket deals in Kosovo",
    "two_stores": "Maximum 2 stores",
    "weak_deal": "Weak deal",
}
