"""Albanian UI strings."""

STRINGS = {
    "add": "Shto",
    "all": "Të gjitha",
    "any_store": "Më lirë gjithsej",
    "app_title": "OfertaKS",
    "average_deal": "Ofertë mesatare",
    "basket": "Lista e blerjeve",
    "best_deals": "Ofertat më të mira",
    "best_price": "Çmimi më i mirë",
    "clear": "Pastro",
    "copy_diagnostics": "Kopjo raportin",
    "details": "Detaje",
    "diagnostics": "Diagnostika",
    "excellent_deal": "Ofertë shumë e mirë",
    "favorites": "Të preferuarat",
    "good_deal": "Ofertë e mirë",
    "home": "Kryefaqja",
    "language": "Gjuha",
    "language_saved": "Gjuha u ruajt",
    "largest_discount": "Zbritja më e madhe",
    "last_sync": "Përditësimi i fundit",
    "missing_items": "mungojnë",
    "nearby": "Pranë meje",
    "newest": "Më të rejat",
    "no_offers": "Nuk u gjetën oferta.",
    "not_enough_history": "Nuk ka histori të mjaftueshme",
    "not_matched": "nuk u gjet",
    "offers": "Ofertat",
    "offline_data": "Të dhëna offline",
    "one_store": "Një dyqan",
    "price_history": "Historia e çmimit",
    "price_per_unit": "Çmimi për njësi",
    "recipes": "Receta",
    "refresh": "Rifresko",
    "retry": "Provo përsëri",
    "search": "Kërko produkt",
    "settings": "Cilësimet",
    "sort_best_deals": "Ofertat më të mira",
    "sort_lowest_price": "Çmimi më i ulët",
    "stores": "Dyqanet",
    "syncing": "Duke rifreskuar ofertat...",
    "tagline": "Ofertat më të mira në Kosovë",
    "two_stores": "Maksimumi 2 dyqane",
    "weak_deal": "Ofertë e dobët",
}
