"""French UI strings."""

STRINGS = {
    "add": "Ajouter",
    "all": "Tous",
    "any_store": "Moins cher au total",
    "app_title": "OfertaKS",
    "average_deal": "Offre moyenne",
    "basket": "Liste de courses",
    "best_deals": "Meilleures offres",
    "best_price": "Meilleur prix",
    "clear": "Effacer",
    "copy_diagnostics": "Copier le rapport",
    "details": "Détails",
    "diagnostics": "Diagnostic",
    "excellent_deal": "Excellente offre",
    "favorites": "Favoris",
    "good_deal": "Bonne offre",
    "home": "Accueil",
    "language": "Langue",
    "language_saved": "Langue enregistrée",
    "largest_discount": "Réduction la plus forte",
    "last_sync": "Dernière mise à jour",
    "missing_items": "manquant(s)",
    "nearby": "À proximité",
    "newest": "Plus récent",
    "no_offers": "Aucune offre trouvée.",
    "not_enough_history": "Pas assez d'historique",
    "not_matched": "non trouvé",
    "offers": "Offres",
    "offline_data": "Données hors ligne",
    "one_store": "Un seul magasin",
    "price_history": "Historique des prix",
    "price_per_unit": "Prix par unité",
    "recipes": "Recettes",
    "refresh": "Actualiser",
    "retry": "Réessayer",
    "search": "Rechercher un produit",
    "settings": "Réglages",
    "sort_best_deals": "Meilleures offres",
    "sort_lowest_price": "Prix le plus bas",
    "stores": "Magasins",
    "syncing": "Actualisation des offres...",
    "tagline": "Les meilleures offres au Kosovo",
    "two_stores": "Maximum 2 magasins",
    "weak_deal": "Offre faible",
}
