"""English UI strings."""

STRINGS = {
    "add": "Add",
    "all": "All",
    "any_store": "Cheapest overall",
    "app_title": "OfertaKS",
    "average_deal": "Average deal",
    "basket": "Shopping list",
    "best_deals": "Best offers",
    "best_price": "Best price",
    "clear": "Clear",
    "copy_diagnostics": "Copy diagnostic report",
    "details": "Details",
    "diagnostics": "Diagnostics",
    "excellent_deal": "Excellent deal",
    "favorites": "Favorites",
    "good_deal": "Good deal",
    "home": "Home",
    "language": "Language",
    "language_saved": "Language saved",
    "largest_discount": "Largest discount",
    "last_sync": "Last updated",
    "missing_items": "missing",
    "nearby": "Nearby",
    "newest": "Newest",
    "no_offers": "No offers found.",
    "not_enough_history": "Not enough history",
    "not_matched": "not matched",
    "offers": "Offers",
    "offline_data": "Offline data",
    "one_store": "One store",
    "price_history": "Price history",
    "price_per_unit": "Price per unit",
    "recipes": "Recipes",
    "refresh": "Refresh",
    "retry": "Retry",
    "search": "Search product",
    "settings": "Settings",
    "sort_best_deals": "Best offers",
    "sort_lowest_price": "Lowest price",
    "stores": "Stores",
    "syncing": "Refreshing offers...",
    "tagline": "Best supermarket deals in Kosovo",
    "two_stores": "Maximum 2 stores",
    "weak_deal": "Weak deal",
    "back": "Back",
    "bakery": "Bakery",
    "cache_writable": "Cache writable",
    "category": "Category",
    "category_dairy": "Dairy",
    "category_drinks": "Drinks",
    "category_frozen": "Frozen",
    "category_fruits_vegetables": "Fruits & Vegetables",
    "category_meat_fish": "Meat & Fish",
    "category_other_food": "Other Food",
    "category_pantry": "Pantry",
    "category_snacks": "Snacks",
    "cheapest_in_category": "Cheapest in category",
    "current_price": "Current price",
    "current_prices": "Current prices",
    "database_writable": "Database writable",
    "discount": "Discount",
    "diagnostic_ok": "OK",
    "diagnostic_unavailable": "Unavailable",
    "food_offers": "Food offers",
    "good_value": "Good value",
    "hide_raw_report": "Hide raw report",
    "live_stores": "Live stores",
    "local_products": "Local products",
    "merchant": "Merchant",
    "merchant_count": "Merchants",
    "merchant_required": "Enter a merchant",
    "no_current_prices": "No current comparable prices",
    "notes": "Note",
    "observed_now": "Observed now",
    "origin": "Origin",
    "origin_confidence": "Origin confidence",
    "origin_confidence_probable": "Probable",
    "origin_confidence_unknown": "Unknown",
    "origin_confidence_verified": "Verified",
    "origin_explanation_flyer": "Origin reported in a flyer or source page",
    "origin_explanation_observation": "Origin reported from an observation",
    "origin_explanation_unknown": "No origin evidence available",
    "origin_region": "Origin region",
    "origin_source": "Origin source",
    "origin_source_flyer": "Flyer",
    "origin_source_merchant": "Merchant",
    "origin_source_official_data": "Official data",
    "origin_source_product_packaging": "Packaging",
    "origin_source_store_label": "Store label",
    "origin_source_unknown": "Unknown",
    "origin_source_user_observation": "User observation",
    "origin_unknown": "Unknown origin",
    "photo_path": "Photo path (optional)",
    "price": "Price",
    "price_cheap": "Cheaper than usual",
    "price_exceptional": "Exceptionally cheap",
    "price_expensive": "Somewhat expensive",
    "price_high": "Above usual price",
    "price_history_explanation": "Compared with at least three observed prices for this product.",
    "price_normal": "Usual price",
    "previous_price": "Previous price",
    "price_required": "Enter a valid price",
    "price_status": "Price status",
    "price_update_saved": "Price update saved locally",
    "product": "Product",
    "quality": "Quality",
    "quality_average": "Average",
    "quality_good": "Good",
    "quality_needs_check": "Needs checking",
    "quantity": "Quantity",
    "recently_updated": "Recently updated",
    "save_price_update": "Save price update",
    "scraper_statuses": "Store source status",
    "show_raw_report": "Show raw report",
    "store_count": "Tracked stores",
    "store_status_interex_partial": "Partial: flyer found; OCR needed",
    "store_status_live": "Live prices available",
    "store_status_not_implemented": "Not implemented",
    "store_status_viva_partial": "Partial: image-based offers need OCR",
    "status_failed": "Failed",
    "status_never_run": "Not run yet",
    "status_partial": "Partial",
    "status_running": "Running",
    "status_success": "Successful",
    "total_offers": "Total offers",
    "translation_service": "Translations available",
    "unit": "Unit",
    "update_price": "Update price",
    "update_price_for": "Update price for",
    "add_place": "Add place",
    "add_product": "Add product",
    "all_food": "All food",
    "availability_current": "Current",
    "availability_stale": "Stale",
    "availability_unknown": "Unknown",
    "bakeries": "Bakeries",
    "basket_short": "List",
    "butchers_fish": "Butchers & fish",
    "community": "Community",
    "description": "Description",
    "directions": "Directions",
    "directions_unavailable": "Directions need a future route provider",
    "fruit_vegetables": "Fruit & vegetables",
    "latitude": "Latitude",
    "local_shops": "Local shops",
    "location_required": "Enter a valid map location",
    "longitude": "Longitude",
    "map": "Map",
    "map_type_bakery": "Bakery",
    "map_type_butcher": "Butcher",
    "map_type_convenience": "Convenience shop",
    "map_type_dairy": "Dairy",
    "map_type_farm": "Farm / local food",
    "map_type_fish": "Fish shop",
    "map_type_fruit_vegetable": "Fruit & vegetables",
    "map_type_grocery": "Grocery",
    "map_type_market": "Market",
    "map_type_market_stall": "Market stall",
    "map_type_specialty_food": "Specialty food",
    "map_type_street_vendor": "Street vendor",
    "map_type_supermarket": "Supermarket",
    "markets": "Markets",
    "merchant_type": "Merchant type",
    "no_recent_observations": "No recent merchant observations",
    "no_recent_product_information": "No recent information for this product",
    "opening_hours": "Opening hours",
    "place_closed": "Place closed",
    "place_name": "Place name (optional)",
    "places_refresh_failed": "Could not refresh places; cached places remain available",
    "places_updated": "Places updated",
    "product_observation_saved": "Product observation saved locally",
    "product_required": "Enter a product",
    "refresh_places": "Refresh places",
    "refreshing_places": "Refreshing Prishtina places...",
    "report_saved_locally": "Report saved locally for later review",
    "save_place": "Save place",
    "show_on_map": "Show on map",
    "showing_on_map": "Showing on map",
    "source_openstreetmap": "OpenStreetMap",
    "store_status_location_only": "Locations available; prices not automated",
    "supermarkets": "Supermarkets",
    "duplicate": "Duplicate",
    "legend": "Legend",
    "unnamed_community_place": "Unnamed community food place",
    "unverified": "Unverified",
    "use_my_location": "Use my location",
    "verified": "Verified",
    "wrong_category": "Wrong category",
    "wrong_location": "Wrong location",
    "price_integrity_exceptional": "Exceptional deal",
    "price_integrity_good": "Good deal",
    "price_integrity_normal": "Normal price",
    "price_integrity_expensive": "Expensive",
    "price_integrity_very_expensive": "Very expensive",
    "price_integrity_weak_promotion": "Weak promotion",
    "price_integrity_insufficient_history": "Not enough history",
    "price_reference": "Reference price",
    "price_warnings": "Price warnings",
    "exceptional_prices": "exceptional prices",
    "good_prices": "good prices",
    "best_nearby_price": "Best nearby price",
    "no_current_deals": "No current deal evidence",
}
