"""English UI strings."""

STRINGS = {
    "add": "Add",
    "all": "All",
    "any_store": "Cheapest overall",
    "app_title": "OfertaKS",
    "average_deal": "Average deal",
    "basket": "Shopping list",
    "best_deals": "Best offers",
    "best_price": "Best price",
    "clear": "Clear",
    "copy_diagnostics": "Copy diagnostic report",
    "details": "Details",
    "diagnostics": "Diagnostics",
    "excellent_deal": "Excellent deal",
    "favorites": "Favorites",
    "good_deal": "Good deal",
    "home": "Home",
    "language": "Language",
    "language_saved": "Language saved",
    "largest_discount": "Largest discount",
    "last_sync": "Last updated",
    "missing_items": "missing",
    "nearby": "Nearby",
    "newest": "Newest",
    "no_offers": "No offers found.",
    "not_enough_history": "Not enough history",
    "not_matched": "not matched",
    "offers": "Offers",
    "offline_data": "Offline data",
    "one_store": "One store",
    "price_history": "Price history",
    "price_per_unit": "Price per unit",
    "recipes": "Recipes",
    "refresh": "Refresh",
    "retry": "Retry",
    "search": "Search product",
    "settings": "Settings",
    "sort_best_deals": "Best offers",
    "sort_lowest_price": "Lowest price",
    "stores": "Stores",
    "syncing": "Refreshing offers...",
    "tagline": "Best supermarket deals in Kosovo",
    "two_stores": "Maximum 2 stores",
    "weak_deal": "Weak deal",
    "back": "Back",
    "bakery": "Bakery",
    "cache_writable": "Cache writable",
    "category": "Category",
    "category_dairy": "Dairy",
    "category_drinks": "Drinks",
    "category_frozen": "Frozen",
    "category_fruits_vegetables": "Fruits & Vegetables",
    "category_meat_fish": "Meat & Fish",
    "category_other_food": "Other Food",
    "category_pantry": "Pantry",
    "category_snacks": "Snacks",
    "cheapest_in_category": "Cheapest in category",
    "current_price": "Current price",
    "current_prices": "Current prices",
    "database_writable": "Database writable",
    "discount": "Discount",
    "diagnostic_ok": "OK",
    "diagnostic_unavailable": "Unavailable",
    "food_offers": "Food offers",
    "good_value": "Good value",
    "hide_raw_report": "Hide raw report",
    "live_stores": "Live stores",
    "local_products": "Local products",
    "merchant": "Merchant",
    "merchant_count": "Merchants",
    "merchant_required": "Enter a merchant",
    "no_current_prices": "No current comparable prices",
    "notes": "Note",
    "observed_now": "Observed now",
    "origin": "Origin",
    "origin_confidence": "Origin confidence",
    "origin_confidence_probable": "Probable",
    "origin_confidence_unknown": "Unknown",
    "origin_confidence_verified": "Verified",
    "origin_explanation_flyer": "Origin reported in a flyer or source page",
    "origin_explanation_observation": "Origin reported from an observation",
    "origin_explanation_unknown": "No origin evidence available",
    "origin_region": "Origin region",
    "origin_source": "Origin source",
    "origin_source_flyer": "Flyer",
    "origin_source_merchant": "Merchant",
    "origin_source_official_data": "Official data",
    "origin_source_product_packaging": "Packaging",
    "origin_source_store_label": "Store label",
    "origin_source_unknown": "Unknown",
    "origin_source_user_observation": "User observation",
    "origin_unknown": "Unknown origin",
    "photo_path": "Photo path (optional)",
    "price": "Price",
    "price_cheap": "Cheaper than usual",
    "price_exceptional": "Exceptionally cheap",
    "price_expensive": "Somewhat expensive",
    "price_high": "Above usual price",
    "price_history_explanation": "Compared with at least three observed prices for this product.",
    "price_normal": "Usual price",
    "previous_price": "Previous price",
    "price_required": "Enter a valid price",
    "price_status": "Price status",
    "price_update_saved": "Price update saved locally",
    "product": "Product",
    "quality": "Quality",
    "quality_average": "Average",
    "quality_good": "Good",
    "quality_needs_check": "Needs checking",
    "quantity": "Quantity",
    "recently_updated": "Recently updated",
    "save_price_update": "Save price update",
    "scraper_statuses": "Store source status",
    "show_raw_report": "Show raw report",
    "store_count": "Tracked stores",
    "store_status_interex_partial": "Partial: flyer found; OCR needed",
    "store_status_live": "Live prices available",
    "store_status_not_implemented": "Not implemented",
    "store_status_viva_partial": "Partial: image-based offers need OCR",
    "status_failed": "Failed",
    "status_never_run": "Not run yet",
    "status_partial": "Partial",
    "status_running": "Running",
    "status_success": "Successful",
    "total_offers": "Total offers",
    "translation_service": "Translations available",
    "unit": "Unit",
    "update_price": "Update price",
    "update_price_for": "Update price for",
}
