"""French UI strings."""

STRINGS = {
    "add": "Ajouter",
    "all": "Tous",
    "any_store": "Moins cher au total",
    "app_title": "OfertaKS",
    "average_deal": "Offre moyenne",
    "basket": "Liste de courses",
    "best_deals": "Meilleures offres",
    "best_price": "Meilleur prix",
    "clear": "Effacer",
    "copy_diagnostics": "Copier le rapport",
    "details": "Détails",
    "diagnostics": "Diagnostic",
    "excellent_deal": "Excellente offre",
    "favorites": "Favoris",
    "good_deal": "Bonne offre",
    "home": "Accueil",
    "language": "Langue",
    "language_saved": "Langue enregistrée",
    "largest_discount": "Réduction la plus forte",
    "last_sync": "Dernière mise à jour",
    "missing_items": "manquant(s)",
    "nearby": "À proximité",
    "newest": "Plus récent",
    "no_offers": "Aucune offre trouvée.",
    "not_enough_history": "Pas assez d'historique",
    "not_matched": "non trouvé",
    "offers": "Offres",
    "offline_data": "Données hors ligne",
    "one_store": "Un seul magasin",
    "price_history": "Historique des prix",
    "price_per_unit": "Prix par unité",
    "recipes": "Recettes",
    "refresh": "Actualiser",
    "retry": "Réessayer",
    "search": "Rechercher un produit",
    "settings": "Réglages",
    "sort_best_deals": "Meilleures offres",
    "sort_lowest_price": "Prix le plus bas",
    "stores": "Magasins",
    "syncing": "Actualisation des offres...",
    "tagline": "Les meilleures offres au Kosovo",
    "two_stores": "Maximum 2 magasins",
    "weak_deal": "Offre faible",
    "back": "Retour",
    "bakery": "Boulangerie",
    "cache_writable": "Cache accessible en écriture",
    "category": "Catégorie",
    "category_dairy": "Produits laitiers",
    "category_drinks": "Boissons",
    "category_frozen": "Surgelés",
    "category_fruits_vegetables": "Fruits et légumes",
    "category_meat_fish": "Viande et poisson",
    "category_other_food": "Autre alimentaire",
    "category_pantry": "Épicerie",
    "category_snacks": "Snacks",
    "cheapest_in_category": "Moins cher par catégorie",
    "current_price": "Prix actuel",
    "current_prices": "Prix actuels",
    "database_writable": "Base de données accessible en écriture",
    "discount": "Réduction",
    "diagnostic_ok": "OK",
    "diagnostic_unavailable": "Indisponible",
    "food_offers": "Offres alimentaires",
    "good_value": "Bon rapport qualité-prix",
    "hide_raw_report": "Masquer le rapport brut",
    "live_stores": "Magasins en direct",
    "local_products": "Produits locaux",
    "merchant": "Commerçant",
    "merchant_count": "Commerçants",
    "merchant_required": "Saisissez un commerçant",
    "no_current_prices": "Aucun prix actuel comparable",
    "notes": "Note",
    "observed_now": "Observé maintenant",
    "origin": "Origine",
    "origin_confidence": "Fiabilité de l'origine",
    "origin_confidence_probable": "Probable",
    "origin_confidence_unknown": "Inconnue",
    "origin_confidence_verified": "Vérifiée",
    "origin_explanation_flyer": "Origine indiquée dans un prospectus ou une page source",
    "origin_explanation_observation": "Origine signalée par une observation",
    "origin_explanation_unknown": "Aucune preuve d'origine disponible",
    "origin_region": "Région d'origine",
    "origin_source": "Source de l'origine",
    "origin_source_flyer": "Prospectus",
    "origin_source_merchant": "Commerçant",
    "origin_source_official_data": "Données officielles",
    "origin_source_product_packaging": "Emballage",
    "origin_source_store_label": "Étiquette du magasin",
    "origin_source_unknown": "Inconnue",
    "origin_source_user_observation": "Observation utilisateur",
    "origin_unknown": "Origine inconnue",
    "photo_path": "Chemin de la photo (facultatif)",
    "price": "Prix",
    "price_cheap": "Moins cher que d'habitude",
    "price_exceptional": "Exceptionnellement bon marché",
    "price_expensive": "Un peu cher",
    "price_high": "Au-dessus du prix habituel",
    "price_history_explanation": "Comparé à au moins trois prix observés pour ce produit.",
    "price_normal": "Prix habituel",
    "previous_price": "Prix précédent",
    "price_required": "Saisissez un prix valide",
    "price_status": "Niveau de prix",
    "price_update_saved": "Mise à jour du prix enregistrée localement",
    "product": "Produit",
    "quality": "Qualité",
    "quality_average": "Moyenne",
    "quality_good": "Bonne",
    "quality_needs_check": "À vérifier",
    "quantity": "Quantité",
    "recently_updated": "Mis à jour récemment",
    "save_price_update": "Enregistrer le prix",
    "scraper_statuses": "État des sources magasins",
    "show_raw_report": "Afficher le rapport brut",
    "store_count": "Magasins suivis",
    "store_status_interex_partial": "Partiel : prospectus trouvé, OCR nécessaire",
    "store_status_live": "Prix en direct disponibles",
    "store_status_not_implemented": "Non implémenté",
    "store_status_viva_partial": "Partiel : offres en images, OCR nécessaire",
    "status_failed": "Échec",
    "status_never_run": "Pas encore exécuté",
    "status_partial": "Partiel",
    "status_running": "En cours",
    "status_success": "Réussi",
    "total_offers": "Offres totales",
    "translation_service": "Traductions disponibles",
    "unit": "Unité",
    "update_price": "Mettre à jour le prix",
    "update_price_for": "Mettre à jour le prix de",
}
