"""Albanian UI strings."""

STRINGS = {
    "add": "Shto",
    "all": "Të gjitha",
    "any_store": "Më lirë gjithsej",
    "app_title": "OfertaKS",
    "average_deal": "Ofertë mesatare",
    "basket": "Lista e blerjeve",
    "best_deals": "Ofertat më të mira",
    "best_price": "Çmimi më i mirë",
    "clear": "Pastro",
    "copy_diagnostics": "Kopjo raportin",
    "details": "Detaje",
    "diagnostics": "Diagnostika",
    "excellent_deal": "Ofertë shumë e mirë",
    "favorites": "Të preferuarat",
    "good_deal": "Ofertë e mirë",
    "home": "Kryefaqja",
    "language": "Gjuha",
    "language_saved": "Gjuha u ruajt",
    "largest_discount": "Zbritja më e madhe",
    "last_sync": "Përditësimi i fundit",
    "missing_items": "mungojnë",
    "nearby": "Pranë meje",
    "newest": "Më të rejat",
    "no_offers": "Nuk u gjetën oferta.",
    "not_enough_history": "Nuk ka histori të mjaftueshme",
    "not_matched": "nuk u gjet",
    "offers": "Ofertat",
    "offline_data": "Të dhëna offline",
    "one_store": "Një dyqan",
    "price_history": "Historia e çmimit",
    "price_per_unit": "Çmimi për njësi",
    "recipes": "Receta",
    "refresh": "Rifresko",
    "retry": "Provo përsëri",
    "search": "Kërko produkt",
    "settings": "Cilësimet",
    "sort_best_deals": "Ofertat më të mira",
    "sort_lowest_price": "Çmimi më i ulët",
    "stores": "Dyqanet",
    "syncing": "Duke rifreskuar ofertat...",
    "tagline": "Ofertat më të mira në Kosovë",
    "two_stores": "Maksimumi 2 dyqane",
    "weak_deal": "Ofertë e dobët",
    "back": "Kthehu",
    "bakery": "Furra buke",
    "cache_writable": "Cache mund të shkruhet",
    "category": "Kategoria",
    "category_dairy": "Bulmet",
    "category_drinks": "Pije",
    "category_frozen": "Të ngrira",
    "category_fruits_vegetables": "Fruta dhe perime",
    "category_meat_fish": "Mish dhe peshk",
    "category_other_food": "Ushqime të tjera",
    "category_pantry": "Ushqime bazë",
    "category_snacks": "Snacks",
    "cheapest_in_category": "Më e lira në kategori",
    "current_price": "Çmimi aktual",
    "current_prices": "Çmimet aktuale",
    "database_writable": "Baza e të dhënave mund të shkruhet",
    "discount": "Zbritja",
    "diagnostic_ok": "Në rregull",
    "diagnostic_unavailable": "Nuk është në dispozicion",
    "food_offers": "Oferta ushqimore",
    "good_value": "Vlerë e mirë",
    "hide_raw_report": "Fshih raportin e papërpunuar",
    "live_stores": "Dyqane me çmime live",
    "local_products": "Produkte lokale",
    "merchant": "Shitësi",
    "merchant_count": "Shitësit",
    "merchant_required": "Shkruani një shitës",
    "no_current_prices": "Nuk ka çmime aktuale të krahasueshme",
    "notes": "Shënim",
    "observed_now": "Vërejtur tani",
    "origin": "Origjina",
    "origin_confidence": "Besueshmëria e origjinës",
    "origin_confidence_probable": "E mundshme",
    "origin_confidence_unknown": "E panjohur",
    "origin_confidence_verified": "E verifikuar",
    "origin_explanation_flyer": "Origjina raportohet në fletushkë ose në faqen burimore",
    "origin_explanation_observation": "Origjina raportohet nga një vëzhgim",
    "origin_explanation_unknown": "Nuk ka dëshmi për origjinën",
    "origin_region": "Rajoni i origjinës",
    "origin_source": "Burimi i origjinës",
    "origin_source_flyer": "Fletushkë",
    "origin_source_merchant": "Shitësi",
    "origin_source_official_data": "Të dhëna zyrtare",
    "origin_source_product_packaging": "Paketimi",
    "origin_source_store_label": "Etiketa e dyqanit",
    "origin_source_unknown": "I panjohur",
    "origin_source_user_observation": "Vëzhgim i përdoruesit",
    "origin_unknown": "Origjinë e panjohur",
    "photo_path": "Rruga e fotos (opsionale)",
    "price": "Çmimi",
    "price_cheap": "Më lirë se zakonisht",
    "price_exceptional": "Jashtëzakonisht lirë",
    "price_expensive": "Disi e shtrenjtë",
    "price_high": "Mbi çmimin e zakonshëm",
    "price_history_explanation": "Krahasuar me të paktën tre çmime të vëzhguara për këtë produkt.",
    "price_normal": "Çmim i zakonshëm",
    "previous_price": "Çmimi i mëparshëm",
    "price_required": "Shkruani një çmim të vlefshëm",
    "price_status": "Gjendja e çmimit",
    "price_update_saved": "Përditësimi i çmimit u ruajt lokalisht",
    "product": "Produkti",
    "quality": "Cilësia",
    "quality_average": "Mesatare",
    "quality_good": "E mirë",
    "quality_needs_check": "Duhet kontrolluar",
    "quantity": "Sasia",
    "recently_updated": "Përditësuar së fundmi",
    "save_price_update": "Ruaj përditësimin e çmimit",
    "scraper_statuses": "Gjendja e burimeve të dyqaneve",
    "show_raw_report": "Shfaq raportin e papërpunuar",
    "store_count": "Dyqane të ndjekura",
    "store_status_interex_partial": "Pjesërisht: u gjet fletushka, duhet OCR",
    "store_status_live": "Çmimet live janë në dispozicion",
    "store_status_not_implemented": "Nuk është implementuar",
    "store_status_viva_partial": "Pjesërisht: ofertat me imazh kanë nevojë për OCR",
    "status_failed": "Dështoi",
    "status_never_run": "Ende nuk është ekzekutuar",
    "status_partial": "Pjesërisht",
    "status_running": "Duke u ekzekutuar",
    "status_success": "Me sukses",
    "total_offers": "Oferta gjithsej",
    "translation_service": "Përkthimet janë në dispozicion",
    "unit": "Njësia",
    "update_price": "Përditëso çmimin",
    "update_price_for": "Përditëso çmimin për",
}
